### ISSUE TITLE
Error occurs in json-readtable

### ISSUE THREAD

**Issue by Rindrics** [misohena/gcal#1]
Thank you for making great feature!
But an error occurs in json-readtable in my env so would you give me some advice?
The error messages was as follows (may be containing my id and secret).

Thanks.
--------------------------------------------------------------------------------------------

Debugger entered--Lisp error: (json-readtable-error)
  signal(json-readtable-error nil)
  json-read()
  json-read-from-string("\nContent-Type: application/json; charset=UTF-8\nContent-Encoding: gzip\nDate: Wed, 01 Aug 2018 20:08:34 GMT\nExpires: Wed, 01 Aug 2018 20:08:34 GMT\nCache-Control: private, max-age=0\nX-Content-Type-Options: nosniff\nX-Frame-Options: SAMEORIGIN\nX-XSS-Protection: 1; mode=block\nServer: GSE\nAlt-Svc: quic=\":443\"; ma=2592000; v=\"44,43,39,35\"\nTransfer-Encoding: chunked\n\n{\n \"error\": \"invalid_request\",\n \"error_description\": \"Credentials in post body and basic Authorization header do not match\"\n}\n")
  (let* ((status (nth 0 response)) (body (nth 3 response))) (json-read-from-string (decode-coding-string body (quote utf-8))))
  gcal-http-response-to-json((400 "Bad Request" nil "\nContent-Type: application/json; charset=UTF-8\nContent-Encoding: gzip\nDate: Wed, 01 Aug 2018 20:08:34 GMT\nExpires: Wed, 01 Aug 2018 20:08:34 GMT\nCache-Control: private, max-age=0\nX-Content-Type-Options: nosniff\nX-Frame-Options: SAMEORIGIN\nX-XSS-Protection: 1; mode=block\nServer: GSE\nAlt-Svc: quic=\":443\"; ma=2592000; v=\"44,43,39,35\"\nTransfer-Encoding: chunked\n\n{\n \"error\": \"invalid_request\",\n \"error_description\": \"Credentials in post body and basic Authorization header do not match\"\n}\n"))
  gcal-retrieve-json-post-www-form("https://www.googleapis.com/oauth2/v3/token" (("client_id" "377298149524-04nllr64g7pippih2r0vth5a206gff3q.apps.googleusercontent.com") ("client_secret" "SxvbT6t6byrWZ6CIm5_FLxsW") ("redirect_uri" "urn:ietf:wg:oauth:2.0:oob") ("grant_type" "authorization_code") ("code" "4/AAD9l07_Pvax0uxQqZQPsACMbzJn88GxZn7Pk1JmdLFmifdoMoKKhp0")))
  gcal-oauth-get-access-token("https://accounts.google.com/o/oauth2/auth" "https://www.googleapis.com/oauth2/v3/token" "377298149524-04nllr64g7pippih2r0vth5a206gff3q.apps.googleusercontent.com" "SxvbT6t6byrWZ6CIm5_FLxsW" "https://www.googleapis.com/auth/calendar")
  (let* ((result (gcal-oauth-get-access-token auth-url token-url client-id client-secret scope)) (access-token (cdr (assq (quote access_token) result))) (expires-in (cdr (assq (quote expires_in) result))) (refresh-token (cdr (assq (quote refresh_token) result))) (expires (time-add (current-time) (seconds-to-time expires-in)))) (progn "Constructor for objects of type `gcal-oauth-token'." nil (vector (quote cl-struct-gcal-oauth-token) access-token expires refresh-token token-url)))
  gcal-oauth-auth("https://accounts.google.com/o/oauth2/auth" "https://www.googleapis.com/oauth2/v3/token" "377298149524-04nllr64g7pippih2r0vth5a206gff3q.apps.googleusercontent.com" "SxvbT6t6byrWZ6CIm5_FLxsW" "https://www.googleapis.com/auth/calendar")
  (setq token (gcal-oauth-auth auth-url token-url client-id client-secret scope))
  (if token (if (time-less-p (progn nil (or (progn nil (and (vectorp token) (>= ... 5) (memq ... cl-struct-gcal-oauth-token-tags) t)) (signal (quote wrong-type-argument) (list (quote gcal-oauth-token) token))) (aref token 2)) (current-time)) (setq token (gcal-oauth-refresh token client-id client-secret token-url))) (setq token (gcal-oauth-auth auth-url token-url client-id client-secret scope)))
  gcal-oauth-get(nil "https://accounts.google.com/o/oauth2/auth" "https://www.googleapis.com/oauth2/v3/token" "377298149524-04nllr64g7pippih2r0vth5a206gff3q.apps.googleusercontent.com" "SxvbT6t6byrWZ6CIm5_FLxsW" "https://www.googleapis.com/auth/calendar")
  (setq gcal-access-token (gcal-oauth-get gcal-access-token gcal-auth-url gcal-token-url gcal-client-id gcal-client-secret gcal-scope-url))
  gcal-access-token()
  (list "access_token" (gcal-access-token))
  (cons (list "access_token" (gcal-access-token)) (cons (list "key" gcal-client-secret) (quote (("grant_type" "authorization_code")))))
  (gcal-retrieve-json-get "https://www.googleapis.com/calendar/calendars/akira.hayashi.1987@gmail.com/everts" (cons (list "access_token" (gcal-access-token)) (cons (list "key" gcal-client-secret) (quote (("grant_type" "authorization_code"))))))
  eval((gcal-retrieve-json-get "https://www.googleapis.com/calendar/calendars/akira.hayashi.1987@gmail.com/everts" (cons (list "access_token" (gcal-access-token)) (cons (list "key" gcal-client-secret) (quote (("grant_type" "authorization_code")))))) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

**Comment by misohena** [comment]
こんにちは。

トレースを見ると最初の認証(アクセストークンの取得。gcal-oauth-get-access-token関数)の段階で失敗しているように見えます。
400 Bad Request
Credentials in post body and basic Authorization header do not match
というエラーが返ってきているようですね。

こちらの環境では問題なくトークンが返ってきているようなので原因が分かりません。

すでにご確認かもしれませんが、再度Developer Consoleから取得した情報(gcal-client-id, gcal-client-secret)や入力した認証コード、また、Developer Console上での設定が正しいことをご確認頂けると解消するかもしれません。

また、問題を切り分けるためにEmacsを介さずにアクセストークンを取得してみると原因が分かるかもしれません。

1. gcal-client-id, gcal-client-secret が設定されていることを確認する。

2. 次のlispをEmacsで実行する等してURLを得る。

  (gcal-http-make-query-url
    "https://accounts.google.com/o/oauth2/auth"
    `(("client_id" . ,gcal-client-id)
      ("response_type" . "code")
      ("redirect_uri" . "urn:ietf:wg:oauth:2.0:oob")
      ("scope" . "https://www.googleapis.com/auth/calendar")))

  参考:私の場合次のようになりました
   "https://accounts.google.com/o/oauth2/auth?client_id=(クライアントID)&response_type=code&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar"

3. 2で取得したURLをブラウザのアドレスバーに入れて、開いたページで権限を許可し、コードを得る。

4. 次のlispをEmacsで実行する等してPOSTするjsonデータを作成する。
  (json-encode `(
     ("client_id" . ,gcal-client-id)
     ("client_secret" . ,gcal-client-secret)
     ("redirect_uri" . "urn:ietf:wg:oauth:2.0:oob")
     ("grant_type" . "authorization_code")
     ("code" . "(3で得られたコード)")))

  参考:私の場合次のようになりました
`
    "{\"client_id\":\"(クライアントID)\",\"client_secret\":\"(クライアントシークレット)\",\"redirect_uri\":\"urn:ietf:wg:oauth:2.0:oob\",\"grant_type\":\"authorization_code\",\"code\":\"(3で得られたコード)\"}"
`

5. wget等のツールでデータをPOSTする。

wget --header="Content-Type: application/json" --post-data="(4で得られたjsonデータ)" https://www.googleapis.com/oauth2/v3/token -O token.json

成功したらアクセストークンがtoken.jsonに保存されるはずです。400エラーになるならEmacs上でやったときと同様のエラーなので、Emacsの外に何か原因があるのだと思います。
