### ISSUE TITLE
Publish for MELPA

### ISSUE THREAD

**Issue by conao3** [misohena/gcal#10]
はじめまして。

MELPAに公開することで、より多くの人がgcalをインストールしやすくなると思います。
どうでしょうか。。？

**Comment by misohena** [comment]
はじめまして。

MELPAは散々お世話になっていますが公開する方法が分からなくて……。
簡単であれば良いのですが検索して出てきた
https://qiita.com/tadsan/items/0d3ed50b260d1e9ae1bd
を見るとなんだか面倒くさそうだなぁというのも。
(英語も大の苦手でして)

**Comment by conao3** [comment]
面倒なのは最初だけですし、サポートしますので大丈夫です!
レシピ登録も面倒であればこちらで出しますー (しかしAuthorの承諾をもらっているというのは一言コメントが必要そうな気もしています。)
