### ISSUE TITLE
Tokenの期限切れについて

### ISSUE THREAD

**Issue by ROCKTAKEY** [misohena/gcal#13]
いつもありがとうございます。

tokenの期限切れが発生した場合、自動でrefreshする機能があると思うのですが、私の手元では、一定期間(長さは不明です)経つとこのrefresh機能でのrefreshができなくなってしまいます(Bad request で、たしかtoken expireが返ってきます)。現状はブラウザから取得していたtokenをまた取得しなおすしかありません。そちらではこのような事象は確認されていないでしょうか。

ちなみに、今のところは以下のようにオーバーライドすることで、tokenが完全に死んだらnilを返却し(whenはelse節がnilの扱い)、再びブラウザから取得するようにしています。

```emacs-lisp
(defun gcal-oauth-refresh (token client-id client-secret &optional token-url)
        "gcal-oauth-token構造体のアクセストークンをリフレッシュします。"
        (let* ((result (gcal-oauth-get-refresh-token
                        (gcal-oauth-token-refresh token)
                        (or token-url (gcal-oauth-token-url token))
                        client-id client-secret))
               (access-token (cdr (assq 'access_token result)))
               (expires-in (cdr (assq 'expires_in result)))
               (expires (time-add (current-time) (seconds-to-time expires-in))))
          (when (and access-token expires)
            (setf (gcal-oauth-token-access token) access-token)
            (setf (gcal-oauth-token-expires token) expires)
            token)))
```

**Comment by misohena** [comment]
すいませんIssue気がついていませんでした。

ああ、やっぱりリフレッシュトークンの失効を考慮していないんですね……。
コードを見直しているときに何となくそんな気がしていました。
再認証が必要でしょうからご指摘の方法で大丈夫だと思いますが、後で調べてみます。
教えて頂きありがとうございます。

https://developers.google.com/identity/protocols/oauth2
によれば有効期間は6ヶ月みたいですね(その他何かのタイミングでも失効するみたい)。

ちなみに私の所ではここ数年で認証し直した記憶はほとんどありません。別の不具合の関係で再認証したことはあったと思います。
たぶんほぼ毎日同期しているからかもしれません。

**Comment by ROCKTAKEY** [comment]
ありがとうございます。いただいたページで初めて、テスト状態だと7日でトークンが切れることを知りました……
通常の状態なら6ヶ月放置しないと切れないとなると、あんまり問題にはならなそうですね

**Comment by misohena** [comment]
修正してみました。
57e58d488e636ce654b09d756b11474584b20cfd

なかなかリフレッシュトークンが失効しないのでテストが大変ですよね。

幸い1年くらい前に再認証したときの以前のトークンファイルが.oldというファイル名で残っていたので、その中のリフレッシュトークンを食わせてみたところ ((error . "invalid_grant") (error_description . "Bad Request")) という結果が返ってきました。

常に invalid_grant なのかよく分からなかったのでエラーの内容は見ずに失敗時は(上でおっしゃっていたようにnilを返して)必ずブラウザ経由で認証コードを再発行するようにしてあります。サーバやネットワークのトラブル、設定ミス等で失敗した可能性もありますが、その場合は認証コードを入力する前にC-gで中断すればトークンファイルは失われないようになっていたので別にいいかなと。ちゃんとやるなら再認証しても意味ないエラーの場合は中断した方が親切なのかもしれません。

**Comment by ROCKTAKEY** [comment]
ありがとうございます！
