### ISSUE TITLE
周期0の繰り返しについて

### ISSUE THREAD

**Issue by ROCKTAKEY** [misohena/gcal#9]
今回はPRでなくてすみません。
org-modeでは、繰り返しの終了日をあらかじめ設定しておくことはできませんが、TODOをDONEにするコマンド(C-c C-t d)にC-u 0を前置することで、TODOをDONEにして繰り返しを終わらせる機能があります(繰り返しTODOは前置なしでDONE化すると即座にTODOになると共に日付が指定周期で更新される)。このとき、agendaで二度と表示されないよう、周期が0になる処理が成されます。

例: 
はじめ
```org-mode
* TODO some
DEADLINE: <2020-05-13 Wed +1w>
```
C-c C-t d (前置引数なし)
```org-mode
* TODO some
DEADLINE: <2020-05-20 Wed +1w>
(たしかオプションで(一瞬)DONEになった履歴が残る)
```
C-u 0 C-c C-t d
```org-mode
* DONE some
DEADLINE: <2020-05-13 Wed +0w>
```

現状、pushの際に+0wが+1wとして認識されているようで、1週ごとに繰り返しています。これは周期とはみなさず当日のみに同期されるべきだと思います。

時間があればPRを出すかもしれませんが、先に共有しておきます。

**Comment by misohena** [comment]
そんな機能があるとは！
と、試してみましたが+0になりません。何か設定があるのでしょうか。
いずれにせよ終わらせたつもりで毎週カレンダーに載ってしまうのは困るでしょうし、0が1と同等に扱われるのも変ですから修正を試みてみます。

**Comment by ROCKTAKEY** [comment]
すみません、前置引数は0ではなくて-1でした。

**Comment by misohena** [comment]
> すみません、前置引数は0ではなくて-1でした。

出来ました！
org-todoの
> With a numeric prefix arg of -1, cancel repeater to allow marking as DONE.

この部分ですね。

それで一応修正してみましたがいかがでしょうか。
6b260b9

**Comment by ROCKTAKEY** [comment]
返事が遅れてすみません。ちゃんと修正されておりました！ありがとうございました！

ちなみに、動作に影響はないですが、ELSE節がない場合、ifではなくwhenを使うことが推奨だった気がします。
